export const API = "http://localhost:8000/products";
export const API_CATEGORIES = "http://localhost:8000/category";
export const ACTIONS = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_ONE_PRODUCT: "GET_ONE_PRODUCT",
  GET_COFFEE_CART: "GET_COFFEE_CART",
  SET_PAYMENT_INFO: "SET_PAYMENT_INFO",
  GET_MB: "GET_MB",
  PLUS_LIKE_COFFEE: "PLUS_LIKE_COFFEE",
  RESET_LIKE_COFFEE: "RESET_LIKE_COFFEE",
};
